version: '3.8'

services:
  # Servidor Web (Apache + PHP)
  web:
    image: litespeedtech/openlitespeed:1.7.16-lsphp52
    container_name: qualidade3_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    restart: always
    depends_on:
      - db

  # Banco de Dados (MySQL)
  db:
    image: mysql:5.6
    container_name: qualidade3_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: qualidade_teste
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - qualidade3_db_data:/var/lib/mysql
      # Automação: Executa o init.sql automaticamente quando o container liga pela primeira vez
      - ./db-init:/docker-entrypoint-initdb.d

# Volume persistente para não perder os dados do banco ao desligar o container
volumes:
  qualidade3_db_data: